version: "3"

services:
  spark-iceberg:
    image: spark-iceberg:latest
    depends_on:
      - postgres
    container_name: spark-iceberg
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
    ports:
      - 8888:8888
      - 8080:8080
      - 18080:18080
  postgres:
    image: postgres:13.4
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=iceberg_catalog
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data